<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ad55fdb2-d80d-4423-abfe-16f74aa24fb4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" Version="7.6.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\V1\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.CatalogService.Application\Pos.CatalogService.Application.csproj" />
    <ProjectReference Include="..\Pos.CatalogService.Infrastructure.Persistence\Pos.CatalogService.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Pos.CatalogService.Infrastructure.Shared\Pos.CatalogService.Infrastructure.Shared.csproj" />
  </ItemGroup>

</Project>
